import {
  FieldOfficer,
  BreadcrumbPoint,
  OfficerStop,
  HardwareTracker,
  VisitLog,
} from '../types';

/**
 * MOCK_OFFICERS: List of realistic agricultural field officers covering
 * all three primary statuses ('active', 'stationary', 'offline') with varied
 * battery levels, telemetry metrics, and rural coverage territories.
 */
export const MOCK_OFFICERS: FieldOfficer[] = [
  {
    id: 'off-01',
    fullName: 'Ramesh Patel',
    name: 'Ramesh Patel',
    roleTitle: 'Senior Agronomist',
    phone: '+91 98251 23456',
    assignedTerritory: 'Vadodara Rural Zone 1',
    currentStatus: 'active',
    status: 'active',
    batteryLevel: 84,
    speedKmh: 38,
    lastSeenAt: '2 mins ago',
    lastPingTime: '2 mins ago',
    currentLocation: {
      latitude: 22.3072,
      longitude: 73.1812,
      speed: 38,
      heading: 45,
      timestamp: Date.now() - 120000,
    },
    hasHardwareTracker: true,
    trackerImei: '864209041284719',
    isCharging: false,
    todayDistanceKm: 42.8,
    todayVisitsCount: 6,
    queuedPingsCount: 14,
  },
  {
    id: 'off-02',
    fullName: 'Sunita Sharma',
    name: 'Sunita Sharma',
    roleTitle: 'Field Extension Officer',
    phone: '+91 98251 78901',
    assignedTerritory: 'Padra North Block',
    currentStatus: 'stationary',
    status: 'stationary',
    batteryLevel: 62,
    speedKmh: 0,
    lastSeenAt: '8 mins ago',
    lastPingTime: '8 mins ago',
    currentLocation: {
      latitude: 22.3421,
      longitude: 73.2145,
      speed: 0,
      heading: 120,
      timestamp: Date.now() - 480000,
    },
    hasHardwareTracker: false,
    isCharging: true,
    todayDistanceKm: 28.3,
    todayVisitsCount: 4,
    queuedPingsCount: 0,
  },
  {
    id: 'off-03',
    fullName: 'Vikram Singh',
    name: 'Vikram Singh',
    roleTitle: 'Fertilizer Inspector',
    phone: '+91 98251 34567',
    assignedTerritory: 'Karjan East Sub-district',
    currentStatus: 'offline',
    status: 'offline',
    batteryLevel: 19,
    speedKmh: 0,
    lastSeenAt: '2.5 hours ago',
    lastPingTime: '2.5 hours ago',
    currentLocation: {
      latitude: 22.2589,
      longitude: 73.1428,
      speed: 0,
      heading: 270,
      timestamp: Date.now() - 3600000 * 2.5,
    },
    hasHardwareTracker: true,
    trackerImei: '864209041284743',
    isCharging: false,
    todayDistanceKm: 14.2,
    todayVisitsCount: 2,
    queuedPingsCount: 14,
  },
  {
    id: 'off-04',
    fullName: 'Amit Verma',
    name: 'Amit Verma',
    roleTitle: 'Crop Protection Specialist',
    phone: '+91 98251 90123',
    assignedTerritory: 'Savli Taluka Highway',
    currentStatus: 'active',
    status: 'active',
    batteryLevel: 92,
    speedKmh: 44,
    lastSeenAt: 'Just now',
    lastPingTime: 'Just now',
    currentLocation: {
      latitude: 22.3812,
      longitude: 73.2389,
      speed: 44,
      heading: 180,
      timestamp: Date.now() - 45000,
    },
    hasHardwareTracker: true,
    trackerImei: '864209041284727',
    isCharging: false,
    todayDistanceKm: 56.1,
    todayVisitsCount: 7,
    queuedPingsCount: 0,
  },
];

// Backward-compatible alias
export const mockOfficers = MOCK_OFFICERS;

/**
 * MOCK_ROUTE_BREADCRUMBS: Chronological sequence of 8 GPS coordinate points
 * simulating an officer's morning rural route travel with realistic speeds (0 to 45 km/h)
 * and a mix of 'mobile_app' and 'hardware_tracker' telemetry sources.
 */
export const MOCK_ROUTE_BREADCRUMBS: BreadcrumbPoint[] = [
  {
    id: 'bc-01',
    officerId: 'off-01',
    latitude: 22.2850,
    longitude: 73.1500,
    speedKmh: 0,
    speed: 0,
    heading: 0,
    batteryLevel: 95,
    source: 'mobile_app',
    recordedAt: '08:30 AM',
    accuracy: 4,
    altitude: 45,
    timestamp: 1718000000000,
    isSynced: true,
  },
  {
    id: 'bc-02',
    officerId: 'off-01',
    latitude: 22.2905,
    longitude: 73.1560,
    speedKmh: 28,
    speed: 28,
    heading: 42,
    batteryLevel: 94,
    source: 'hardware_tracker',
    recordedAt: '08:45 AM',
    accuracy: 5,
    altitude: 46,
    timestamp: 1718000900000,
    isSynced: true,
  },
  {
    id: 'bc-03',
    officerId: 'off-01',
    latitude: 22.2968,
    longitude: 73.1630,
    speedKmh: 42,
    speed: 42,
    heading: 40,
    batteryLevel: 92,
    source: 'hardware_tracker',
    recordedAt: '09:00 AM',
    accuracy: 5,
    altitude: 47,
    timestamp: 1718001800000,
    isSynced: true,
  },
  {
    id: 'bc-04',
    officerId: 'off-01',
    latitude: 22.3020,
    longitude: 73.1710,
    speedKmh: 35,
    speed: 35,
    heading: 55,
    batteryLevel: 90,
    source: 'mobile_app',
    recordedAt: '09:15 AM',
    accuracy: 4,
    altitude: 48,
    timestamp: 1718002700000,
    isSynced: true,
  },
  {
    id: 'bc-05',
    officerId: 'off-01',
    latitude: 22.3055,
    longitude: 73.1780,
    speedKmh: 0,
    speed: 0,
    heading: 85,
    batteryLevel: 88,
    source: 'hardware_tracker',
    recordedAt: '09:30 AM',
    accuracy: 3,
    altitude: 48,
    timestamp: 1718003600000,
    isSynced: true,
  },
  {
    id: 'bc-06',
    officerId: 'off-01',
    latitude: 22.3160,
    longitude: 73.1920,
    speedKmh: 39,
    speed: 39,
    heading: 60,
    batteryLevel: 86,
    source: 'hardware_tracker',
    recordedAt: '10:20 AM',
    accuracy: 5,
    altitude: 51,
    timestamp: 1718006600000,
    isSynced: true,
  },
  {
    id: 'bc-07',
    officerId: 'off-01',
    latitude: 22.3280,
    longitude: 73.2050,
    speedKmh: 0,
    speed: 0,
    heading: 30,
    batteryLevel: 85,
    source: 'mobile_app',
    recordedAt: '10:45 AM',
    accuracy: 4,
    altitude: 53,
    timestamp: 1718008100000,
    isSynced: true,
  },
  {
    id: 'bc-08',
    officerId: 'off-01',
    latitude: 22.3421,
    longitude: 73.2185,
    speedKmh: 24,
    speed: 24,
    heading: 35,
    batteryLevel: 84,
    source: 'hardware_tracker',
    recordedAt: '11:35 AM',
    accuracy: 4,
    altitude: 55,
    timestamp: 1718011100000,
    isSynced: true,
  },
];

// Backward-compatible alias
export const mockRouteBreadcrumbs = MOCK_ROUTE_BREADCRUMBS;

/**
 * MOCK_STOPS: Major stationary visits (>30 minutes) at an agricultural warehouse
 * and a regional dealer shop.
 */
export const MOCK_STOPS: OfficerStop[] = [
  {
    id: 'stop-01',
    officerId: 'off-01',
    latitude: 22.3055,
    longitude: 73.1780,
    stopName: 'Central Agro Seed & Fertilizer Warehouse',
    dealerName: 'Central Agro Seed & Fertilizer Warehouse',
    arrivedAt: '09:30 AM',
    departedAt: '10:15 AM',
    arrivalTime: '09:30 AM',
    departureTime: '10:15 AM',
    durationMinutes: 45,
    dwellMinutes: 45,
    location: { latitude: 22.3055, longitude: 73.1780 },
    address: 'Plot 12, GIDC Industrial Estate, Padra Road',
    purpose: 'Bulk Seed & Fertilizer Dispatch Audit',
    notes: 'Audited 400 DAP bags and verified batch inspection seals.',
    contactPerson: 'Harish Bhai (Warehouse Manager)',
  },
  {
    id: 'stop-02',
    officerId: 'off-01',
    latitude: 22.3280,
    longitude: 73.2050,
    stopName: 'Kisan Seva Kendra Dealer Shop',
    dealerName: 'Kisan Seva Kendra Dealer Shop',
    arrivedAt: '10:45 AM',
    departedAt: '11:25 AM',
    arrivalTime: '10:45 AM',
    departureTime: '11:25 AM',
    durationMinutes: 40,
    dwellMinutes: 40,
    location: { latitude: 22.3280, longitude: 73.2050 },
    address: 'Shop 4, APMC Market Yard, Atladara',
    purpose: 'Pesticide Order & Inventory Inspection',
    notes: 'Verified bio-fertilizer stocks and recorded summer crop orders.',
    contactPerson: 'Jayesh Patel (Owner)',
  },
];

// Backward-compatible alias
export const mockRouteStops = MOCK_STOPS;

export const mockHardwareTrackers: HardwareTracker[] = [
  {
    id: 'trk-01',
    imei: '864209041284719',
    model: 'Teltonika FMB920 Agro',
    assignedOfficerId: 'off-01',
    batteryLevel: 91,
    status: 'active',
    lastSignalTime: '1 min ago',
    firmwareVersion: 'v03.28.04',
  },
  {
    id: 'trk-02',
    imei: '864209041284727',
    model: 'Concox GT06N OBD',
    assignedOfficerId: 'off-02',
    batteryLevel: 76,
    status: 'active',
    lastSignalTime: '6 mins ago',
    firmwareVersion: 'v02.14.01',
  },
  {
    id: 'trk-03',
    imei: '864209041284735',
    model: 'Queclink GL300 Rugged',
    batteryLevel: 100,
    status: 'unpaired',
    lastSignalTime: 'Never',
    firmwareVersion: 'v04.01.12',
  },
  {
    id: 'trk-04',
    imei: '864209041284743',
    model: 'Teltonika FMB920 Agro',
    assignedOfficerId: 'off-03',
    batteryLevel: 14,
    status: 'low_battery',
    lastSignalTime: '2 hours ago',
    firmwareVersion: 'v03.28.04',
  },
];

export const mockVisitLogs: VisitLog[] = [
  {
    id: 'vl-01',
    dealerName: 'Sardar Patel Krishi Kendra',
    officerId: 'off-01',
    officerName: 'Ramesh Patel',
    purpose: 'Fertilizer Inspection',
    notes: 'Sampled 3 lots of bio-fertilizer. Dealer requested next delivery by Friday.',
    latitude: 22.3055,
    longitude: 73.1780,
    timestamp: Date.now() - 3600000 * 3,
    syncStatus: 'synced',
    amountCollected: 15400,
  },
  {
    id: 'vl-02',
    dealerName: 'Shree Ram Agro Center',
    officerId: 'off-01',
    officerName: 'Ramesh Patel',
    purpose: 'Pesticide Order',
    notes: 'Cotton pest infestation reported in block B. Dispensed recommended bio-pesticide demo kits.',
    latitude: 22.3280,
    longitude: 73.2050,
    timestamp: Date.now() - 3600000 * 1.5,
    syncStatus: 'synced',
    amountCollected: 8200,
  },
];
