import {
  FieldOfficer,
  BreadcrumbPoint,
  OfficerStop,
  HardwareTracker,
  VisitLog,
} from '../types';

/**
 * MOCK_OFFICERS: List of realistic agricultural field officers covering
 * all three primary statuses ('active', 'stationary', 'offline') with varied
 * battery levels, telemetry metrics, and rural coverage territories in Pakistan.
 */
export const MOCK_OFFICERS: FieldOfficer[] = [
  {
    id: 'off-01',
    accessCode: 'FO-101',
    ownerId: 'owner-01',
    fullName: 'Muhammad Tariq',
    name: 'Muhammad Tariq',
    roleTitle: 'Senior Agronomist (Zari Mahir)',
    phone: '+92 300 1234567',
    assignedTerritory: 'Multan Cotton & Wheat Zone',
    currentStatus: 'active',
    status: 'active',
    batteryLevel: 84,
    speedKmh: 38,
    lastSeenAt: '2 mins ago',
    lastPingTime: '2 mins ago',
    currentLocation: {
      latitude: 30.1984,
      longitude: 71.4687,
      speed: 38,
      heading: 45,
      timestamp: Date.now() - 120000,
    },
    hasHardwareTracker: true,
    trackerImei: '864209041284719',
    isCharging: false,
    todayDistanceKm: 42.8,
    todayVisitsCount: 6,
    queuedPingsCount: 14,
  },
  {
    id: 'off-02',
    accessCode: 'FO-102',
    ownerId: 'owner-01',
    fullName: 'Zahid Mehmood',
    name: 'Zahid Mehmood',
    roleTitle: 'Field Extension Officer (Zari Muawin)',
    phone: '+92 321 7654321',
    assignedTerritory: 'Faisalabad Crop Circle',
    currentStatus: 'stationary',
    status: 'stationary',
    batteryLevel: 62,
    speedKmh: 0,
    lastSeenAt: '8 mins ago',
    lastPingTime: '8 mins ago',
    currentLocation: {
      latitude: 31.4187,
      longitude: 73.0791,
      speed: 0,
      heading: 120,
      timestamp: Date.now() - 480000,
    },
    hasHardwareTracker: false,
    isCharging: true,
    todayDistanceKm: 28.3,
    todayVisitsCount: 4,
    queuedPingsCount: 0,
  },
  {
    id: 'off-03',
    accessCode: 'FO-103',
    ownerId: 'owner-01',
    fullName: 'Farhan Ali',
    name: 'Farhan Ali',
    roleTitle: 'Fertilizer & Chemical Inspector',
    phone: '+92 333 4567890',
    assignedTerritory: 'Sahiwal Dairy & Maize Belt',
    currentStatus: 'offline',
    status: 'offline',
    batteryLevel: 19,
    speedKmh: 0,
    lastSeenAt: '2.5 hours ago',
    lastPingTime: '2.5 hours ago',
    currentLocation: {
      latitude: 30.6682,
      longitude: 73.1114,
      speed: 0,
      heading: 270,
      timestamp: Date.now() - 3600000 * 2.5,
    },
    hasHardwareTracker: true,
    trackerImei: '864209041284743',
    isCharging: false,
    todayDistanceKm: 14.2,
    todayVisitsCount: 2,
    queuedPingsCount: 14,
  },
  {
    id: 'off-04',
    accessCode: 'FO-104',
    ownerId: 'owner-01',
    fullName: 'Kamran Shahzad',
    name: 'Kamran Shahzad',
    roleTitle: 'Crop Protection Specialist (Tahaffuz-e-Fasl)',
    phone: '+92 302 9876543',
    assignedTerritory: 'Rahim Yar Khan Sugar Belt',
    currentStatus: 'active',
    status: 'active',
    batteryLevel: 92,
    speedKmh: 44,
    lastSeenAt: 'Just now',
    lastPingTime: 'Just now',
    currentLocation: {
      latitude: 28.4212,
      longitude: 70.2989,
      speed: 44,
      heading: 180,
      timestamp: Date.now() - 45000,
    },
    hasHardwareTracker: true,
    trackerImei: '864209041284727',
    isCharging: false,
    todayDistanceKm: 56.1,
    todayVisitsCount: 7,
    queuedPingsCount: 0,
  },
];

// Backward-compatible alias
export const mockOfficers = MOCK_OFFICERS;

/**
 * MOCK_ROUTE_BREADCRUMBS: Chronological sequence of 8 GPS coordinate points
 * simulating an officer's morning rural route travel across the agricultural sector.
 */
export const MOCK_ROUTE_BREADCRUMBS: BreadcrumbPoint[] = [
  {
    id: 'bc-01',
    officerId: 'off-01',
    latitude: 30.1750,
    longitude: 71.4300,
    speedKmh: 0,
    speed: 0,
    heading: 0,
    batteryLevel: 95,
    source: 'mobile_app',
    recordedAt: '08:30 AM',
    accuracy: 4,
    altitude: 122,
    timestamp: 1718000000000,
    isSynced: true,
  },
  {
    id: 'bc-02',
    officerId: 'off-01',
    latitude: 30.1805,
    longitude: 71.4360,
    speedKmh: 28,
    speed: 28,
    heading: 42,
    batteryLevel: 94,
    source: 'hardware_tracker',
    recordedAt: '08:45 AM',
    accuracy: 5,
    altitude: 123,
    timestamp: 1718000900000,
    isSynced: true,
  },
  {
    id: 'bc-03',
    officerId: 'off-01',
    latitude: 30.1868,
    longitude: 71.4430,
    speedKmh: 42,
    speed: 42,
    heading: 40,
    batteryLevel: 92,
    source: 'hardware_tracker',
    recordedAt: '09:00 AM',
    accuracy: 5,
    altitude: 124,
    timestamp: 1718001800000,
    isSynced: true,
  },
  {
    id: 'bc-04',
    officerId: 'off-01',
    latitude: 30.1920,
    longitude: 71.4510,
    speedKmh: 35,
    speed: 35,
    heading: 55,
    batteryLevel: 90,
    source: 'mobile_app',
    recordedAt: '09:15 AM',
    accuracy: 4,
    altitude: 125,
    timestamp: 1718002700000,
    isSynced: true,
  },
  {
    id: 'bc-05',
    officerId: 'off-01',
    latitude: 30.1955,
    longitude: 71.4580,
    speedKmh: 0,
    speed: 0,
    heading: 85,
    batteryLevel: 88,
    source: 'hardware_tracker',
    recordedAt: '09:30 AM',
    accuracy: 3,
    altitude: 125,
    timestamp: 1718003600000,
    isSynced: true,
  },
  {
    id: 'bc-06',
    officerId: 'off-01',
    latitude: 30.2060,
    longitude: 71.4720,
    speedKmh: 39,
    speed: 39,
    heading: 60,
    batteryLevel: 86,
    source: 'hardware_tracker',
    recordedAt: '10:20 AM',
    accuracy: 5,
    altitude: 126,
    timestamp: 1718006600000,
    isSynced: true,
  },
  {
    id: 'bc-07',
    officerId: 'off-01',
    latitude: 30.2180,
    longitude: 71.4850,
    speedKmh: 0,
    speed: 0,
    heading: 30,
    batteryLevel: 85,
    source: 'mobile_app',
    recordedAt: '10:45 AM',
    accuracy: 4,
    altitude: 127,
    timestamp: 1718008100000,
    isSynced: true,
  },
  {
    id: 'bc-08',
    officerId: 'off-01',
    latitude: 30.2321,
    longitude: 71.4985,
    speedKmh: 24,
    speed: 24,
    heading: 35,
    batteryLevel: 84,
    source: 'hardware_tracker',
    recordedAt: '11:35 AM',
    accuracy: 4,
    altitude: 128,
    timestamp: 1718011100000,
    isSynced: true,
  },
];

// Backward-compatible alias
export const mockRouteBreadcrumbs = MOCK_ROUTE_BREADCRUMBS;

/**
 * MOCK_STOPS: Major stationary visits (>30 minutes) at agricultural distribution centres
 * and dealer shops in the district.
 */
export const MOCK_STOPS: OfficerStop[] = [
  {
    id: 'stop-01',
    officerId: 'off-01',
    latitude: 30.1955,
    longitude: 71.4580,
    stopName: 'Ittehad Zari Markaz & Warehouse',
    dealerName: 'Ittehad Zari Markaz & Warehouse',
    arrivedAt: '09:30 AM',
    departedAt: '10:15 AM',
    arrivalTime: '09:30 AM',
    departureTime: '10:15 AM',
    durationMinutes: 45,
    dwellMinutes: 45,
    location: { latitude: 30.1955, longitude: 71.4580 },
    address: 'Ghalla Mandi, Khanewal Road, Multan',
    purpose: 'Bulk Urea & DAP Fertilizer Stock Audit',
    notes: 'Audited 500 bags of Sona Urea and verified lot verification seals.',
    contactPerson: 'Chaudhry Tariq (Warehouse Incharge)',
  },
  {
    id: 'stop-02',
    officerId: 'off-01',
    latitude: 30.2180,
    longitude: 71.4850,
    stopName: 'Kissan Madadgar Zarai Services',
    dealerName: 'Kissan Madadgar Zarai Services',
    arrivedAt: '10:45 AM',
    departedAt: '11:25 AM',
    arrivalTime: '10:45 AM',
    departureTime: '11:25 AM',
    durationMinutes: 40,
    dwellMinutes: 40,
    location: { latitude: 30.2180, longitude: 71.4850 },
    address: 'Shop 14, Grain Market, Jahanian Road',
    purpose: 'Cotton Pest Spray & Bio-pesticide Audit',
    notes: 'Verified cotton spray inventories and recorded summer crop demands.',
    contactPerson: 'Malik Naveed (Dealer Owner)',
  },
];

// Backward-compatible alias
export const mockRouteStops = MOCK_STOPS;

export const mockHardwareTrackers: HardwareTracker[] = [
  {
    id: 'trk-01',
    imei: '864209041284719',
    model: 'Teltonika FMB920 Agro',
    assignedOfficerId: 'off-01',
    batteryLevel: 91,
    status: 'active',
    lastSignalTime: '1 min ago',
    firmwareVersion: 'v03.28.04',
  },
  {
    id: 'trk-02',
    imei: '864209041284727',
    model: 'Concox GT06N OBD',
    assignedOfficerId: 'off-02',
    batteryLevel: 76,
    status: 'active',
    lastSignalTime: '6 mins ago',
    firmwareVersion: 'v02.14.01',
  },
  {
    id: 'trk-03',
    imei: '864209041284735',
    model: 'Queclink GL300 Rugged',
    batteryLevel: 100,
    status: 'unpaired',
    lastSignalTime: 'Never',
    firmwareVersion: 'v04.01.12',
  },
  {
    id: 'trk-04',
    imei: '864209041284743',
    model: 'Teltonika FMB920 Agro',
    assignedOfficerId: 'off-03',
    batteryLevel: 14,
    status: 'low_battery',
    lastSignalTime: '2 hours ago',
    firmwareVersion: 'v03.28.04',
  },
];

export const mockVisitLogs: VisitLog[] = [
  {
    id: 'vl-01',
    dealerName: 'Bismillah Kissan Zarai Markaz',
    officerId: 'off-01',
    officerName: 'Muhammad Tariq',
    purpose: 'Fertilizer Inspection',
    notes: 'Sampled 3 lots of bio-fertilizer. Dealer requested next delivery by Friday.',
    latitude: 30.1955,
    longitude: 71.4580,
    timestamp: Date.now() - 3600000 * 3,
    syncStatus: 'synced',
    amountCollected: 18500,
  },
  {
    id: 'vl-02',
    dealerName: 'Al-Rehman Agri Mall & Seed Corporation',
    officerId: 'off-01',
    officerName: 'Muhammad Tariq',
    purpose: 'Pesticide Order',
    notes: 'Cotton whitefly infestation reported in Sector 4. Advised certified pesticide formula.',
    latitude: 30.2180,
    longitude: 71.4850,
    timestamp: Date.now() - 3600000 * 1.5,
    syncStatus: 'synced',
    amountCollected: 12400,
  },
];
